[package]
name = "ceph-rust"
version = "0.1.10"
authors = ["Chris Jones <chris.jones@lambdastack.io>", "Chris Holcombe"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["ceph", "storage"]
repository = "https://github.com/ceph/ceph-rust"
homepage = "https://github.com/lambdastackio/ceph-rust"
documentation = "https://lambdastackio.github.io/ceph-rust/ceph_rust"
description = """
Official Ceph-rust. A rust-lang specific interface to Ceph librados. You can create a Ceph development environment with the
Chef automation tools: https://github.com/bloomberg/chef-bcs or with ceph-ansible. Chef-bcs uses the ceph-chef cookbook
created and manage at github.com/ceph/ceph-chef. It will build out a full Ceph environment which you can then use
for development etc. See README.md for details.
"""

[dependencies]
bitflags = "~0.7"
byteorder = "~0.5"
libc = "0.2"
nom = "^2.0"
uuid = {version = "~0.3", features = ["use_std"] }

[[bin]]
doc = true
name = "ceph"
path = "examples/ceph.rs"
